# Compose file with services for each module
#
# It automatically builds the images from the sources, though it WILL NOT rebuild them by default.
# You have to run docker compose with the --build flag in order for it to rebuild after changes.
# 
# NOTE: The client will wait a couple of seconds before querying the service to allow for mDNS to do its magic!
#
version: '3'
services:
  broker:
    image: quoco-rest-broker
    container_name: quoco-rest-broker
    build:
      args:
        MODULE: broker
    environment:
      - BROKER_ENDPOINTS=http://quoco-rest-auldfellas:8081/quotations,http://quoco-rest-dodgydrivers:8081/quotations,http://quoco-rest-girlpower:8081/quotations

  auldfellas:
    image: quoco-rest-auldfellas
    container_name: quoco-rest-auldfellas
    build:
      args:
        MODULE: auldfellas

  dodgydrivers:
    image: quoco-rest-dodgydrivers
    container_name: quoco-rest-dodgydrivers
    build:
      args:
        MODULE: dodgydrivers

  girlpower:
    image: quoco-rest-girlpower
    container_name: quoco-rest-girlpower
    build:
      args:
        MODULE: girlpower

  client:
    image: quoco-rest-client
    build:
      args:
        MODULE: client
    depends_on:
      - broker
      - auldfellas
      - dodgydrivers
      - girlpower
    entrypoint: "sh"
    command: "-c 'sleep 5 && java -jar /main.jar'"
    environment:
      - BROKER=http://quoco-rest-broker:8080/applications
