# Compose file with services for each module
#
# It automatically builds the images from the sources, though it WILL NOT rebuild them by default.
# You have to run docker compose with the --build flag in order for it to rebuild after changes.
# 
# NOTE: The client will wait a couple of seconds before querying the service to allow for mDNS to do its magic!
#
version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
    # Expose the admin port for convenience
    - "8161:8161"

  broker:
    image: quoco-rmi-broker
    build:
      args:
        MODULE: broker
    environment:
      - MQ=failover://tcp://activemq:61616

  auldfellas:
    image: quoco-rmi-auldfellas
    build:
      args:
        MODULE: auldfellas
    environment:
      - MQ=failover://tcp://activemq:61616

  dodgydrivers:
    image: quoco-rmi-dodgydrivers
    build:
      args:
        MODULE: dodgydrivers
    environment:
      - MQ=failover://tcp://activemq:61616

  girlpower:
    image: quoco-rmi-girlpower
    build:
      args:
        MODULE: girlpower
    environment:
      - MQ=failover://tcp://activemq:61616

  client:
    image: quoco-rmi-client
    build:
      args:
        MODULE: client
    depends_on:
      - broker
      - auldfellas
      - dodgydrivers
      - girlpower
    entrypoint: "sh"
    command: "-c 'sleep 10 && java -jar /main.jar'"
    environment:
      - MQ=failover://tcp://activemq:61616
